server:
  port: 9000
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery:9000/eureka/

spring:
  application:
    name: eureka-server


